# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adaline_aplicado_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1108, 619)
        MainWindow.setMinimumSize(QtCore.QSize(1108, 619))
        MainWindow.setMaximumSize(QtCore.QSize(1108, 619))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iconfinder_head-atom_64_201494.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(217, 239, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(600, 370, 491, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(207, 227, 255);")
        self.groupBox.setObjectName("groupBox")
        self.grafica_error = MplWidget(self.groupBox)
        self.grafica_error.setGeometry(QtCore.QRect(10, 20, 471, 211))
        self.grafica_error.setObjectName("grafica_error")
        self.pruebas = QtWidgets.QGroupBox(self.centralwidget)
        self.pruebas.setEnabled(False)
        self.pruebas.setGeometry(QtCore.QRect(10, 10, 581, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pruebas.setFont(font)
        self.pruebas.setStyleSheet("background-color:rgb(144, 207, 255)")
        self.pruebas.setObjectName("pruebas")
        self.label = QtWidgets.QLabel(self.pruebas)
        self.label.setGeometry(QtCore.QRect(10, 30, 270, 40))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.pruebas)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 270, 40))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.pruebas)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 270, 40))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.pruebas)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 270, 40))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.pruebas)
        self.label_5.setGeometry(QtCore.QRect(10, 240, 270, 40))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.pruebas)
        self.label_6.setGeometry(QtCore.QRect(10, 290, 270, 40))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.cb_1 = QtWidgets.QComboBox(self.pruebas)
        self.cb_1.setGeometry(QtCore.QRect(320, 30, 241, 31))
        self.cb_1.setStyleSheet("background-color: rgb(197, 235, 255);")
        self.cb_1.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.cb_1.setObjectName("cb_1")
        self.cb_2 = QtWidgets.QComboBox(self.pruebas)
        self.cb_2.setGeometry(QtCore.QRect(320, 80, 241, 31))
        self.cb_2.setStyleSheet("background-color: rgb(197, 235, 255);")
        self.cb_2.setObjectName("cb_2")
        self.cb_3 = QtWidgets.QComboBox(self.pruebas)
        self.cb_3.setGeometry(QtCore.QRect(320, 130, 241, 31))
        self.cb_3.setStyleSheet("background-color: rgb(197, 235, 255);")
        self.cb_3.setObjectName("cb_3")
        self.cb_4 = QtWidgets.QComboBox(self.pruebas)
        self.cb_4.setGeometry(QtCore.QRect(320, 190, 241, 31))
        self.cb_4.setStyleSheet("background-color: rgb(197, 235, 255);")
        self.cb_4.setObjectName("cb_4")
        self.cb_5 = QtWidgets.QComboBox(self.pruebas)
        self.cb_5.setGeometry(QtCore.QRect(320, 250, 241, 31))
        self.cb_5.setStyleSheet("background-color: rgb(197, 235, 255);")
        self.cb_5.setObjectName("cb_5")
        self.cb_6 = QtWidgets.QComboBox(self.pruebas)
        self.cb_6.setGeometry(QtCore.QRect(320, 300, 241, 31))
        self.cb_6.setStyleSheet("background-color: rgb(197, 235, 255);")
        self.cb_6.setObjectName("cb_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(600, 10, 491, 170))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color: rgb(207, 227, 255);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_Entrenar = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_Entrenar.setGeometry(QtCore.QRect(160, 100, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_Entrenar.setFont(font)
        self.btn_Entrenar.setStyleSheet("background-color: rgb(153, 192, 255);")
        self.btn_Entrenar.setObjectName("btn_Entrenar")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(20, 20, 151, 41))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(180, 20, 151, 41))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(340, 20, 151, 41))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.sb_ratio = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.sb_ratio.setGeometry(QtCore.QRect(40, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.sb_ratio.setFont(font)
        self.sb_ratio.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_ratio.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_ratio.setPrefix("")
        self.sb_ratio.setSuffix("")
        self.sb_ratio.setDecimals(5)
        self.sb_ratio.setMinimum(1e-05)
        self.sb_ratio.setMaximum(0.99999)
        self.sb_ratio.setSingleStep(1e-06)
        self.sb_ratio.setProperty("value", 0.5)
        self.sb_ratio.setObjectName("sb_ratio")
        self.sb_epocas = QtWidgets.QSpinBox(self.groupBox_3)
        self.sb_epocas.setGeometry(QtCore.QRect(200, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.sb_epocas.setFont(font)
        self.sb_epocas.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_epocas.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_epocas.setMaximum(50000)
        self.sb_epocas.setProperty("value", 1000)
        self.sb_epocas.setDisplayIntegerBase(10)
        self.sb_epocas.setObjectName("sb_epocas")
        self.sb_error = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.sb_error.setGeometry(QtCore.QRect(360, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.sb_error.setFont(font)
        self.sb_error.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_error.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_error.setPrefix("")
        self.sb_error.setSuffix("")
        self.sb_error.setDecimals(5)
        self.sb_error.setMinimum(1e-05)
        self.sb_error.setMaximum(500.0)
        self.sb_error.setSingleStep(1e-06)
        self.sb_error.setProperty("value", 0.01)
        self.sb_error.setObjectName("sb_error")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(600, 190, 491, 170))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("background-color: rgb(207, 227, 255);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.lbl_error_minimo = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_error_minimo.setGeometry(QtCore.QRect(50, 80, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_error_minimo.setFont(font)
        self.lbl_error_minimo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_error_minimo.setObjectName("lbl_error_minimo")
        self.lbl_convergencia = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_convergencia.setGeometry(QtCore.QRect(50, 120, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_convergencia.setFont(font)
        self.lbl_convergencia.setText("")
        self.lbl_convergencia.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_convergencia.setObjectName("lbl_convergencia")
        self.progreso = QtWidgets.QProgressBar(self.groupBox_4)
        self.progreso.setEnabled(True)
        self.progreso.setGeometry(QtCore.QRect(20, 30, 451, 31))
        self.progreso.setProperty("value", 0)
        self.progreso.setObjectName("progreso")
        self.resultados = QtWidgets.QGroupBox(self.centralwidget)
        self.resultados.setEnabled(False)
        self.resultados.setGeometry(QtCore.QRect(10, 480, 581, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resultados.setFont(font)
        self.resultados.setStyleSheet("background-color:rgb(144, 207, 255)")
        self.resultados.setObjectName("resultados")
        self.resultado = QtWidgets.QLabel(self.resultados)
        self.resultado.setGeometry(QtCore.QRect(80, 40, 351, 71))
        self.resultado.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.resultado.setObjectName("resultado")
        self.btn_Predecir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Predecir.setEnabled(False)
        self.btn_Predecir.setGeometry(QtCore.QRect(200, 390, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_Predecir.setFont(font)
        self.btn_Predecir.setStyleSheet("background-color: rgb(153, 192, 255);")
        self.btn_Predecir.setObjectName("btn_Predecir")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Adaline aplicado"))
        self.groupBox.setTitle(_translate("MainWindow", "Gráfica del error"))
        self.pruebas.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:11pt;\">Seleccione un valor en el rango de 0 a 4, según se sienta menos o más identificado con cada uno de los casos, respectivamente.</span></p></body></html>"))
        self.pruebas.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Seleccione un valor en el rango de 0 a 4, según se sienta menos o más identificado con cada uno de los casos, respectivamente.</span></p></body></html>"))
        self.pruebas.setTitle(_translate("MainWindow", "Preguntas de prueba"))
        self.label.setText(_translate("MainWindow", "1. Sé que podemos ignorar nuestras diferencias, incluso si a veces las cosas se ponen difíciles."))
        self.label_2.setText(_translate("MainWindow", "2. No compartimos tiempo en casa como compañeros"))
        self.label_3.setText(_translate("MainWindow", "3. Creo que un día en el futuro, cuando mire hacia atrás, me dare cuenta que mi esposa y yo estamos en armonía uno con el otro."))
        self.label_4.setText(_translate("MainWindow", "4. Mi esposa y yo tenemos ideas similares sobre cómo debería ser el matrimonio."))
        self.label_5.setText(_translate("MainWindow", "5. Conozco las preocupaciones básicas de mi esposa."))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>6. Podemos empezar una pelea antes de saber lo que está pasando.</p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Controles"))
        self.btn_Entrenar.setText(_translate("MainWindow", "Entrenar"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Ratio de aprendizaje</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Épocas máximas</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Error mínimo</span></p></body></html>"))
        self.sb_ratio.setToolTip(_translate("MainWindow", "<html><head/><body><p>El ratio de aprendizaje debe ser mayor a 0 y menor que 1.</p></body></html>"))
        self.sb_epocas.setToolTip(_translate("MainWindow", "<html><head/><body><p>Las épocas máximas deben ser mayor a 0.</p></body></html>"))
        self.sb_error.setToolTip(_translate("MainWindow", "<html><head/><body><p>El error mínimo debe ser menor a 1.</p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Información extra"))
        self.lbl_error_minimo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\"><br/></span></p></body></html>"))
        self.resultados.setTitle(_translate("MainWindow", "Resultados"))
        self.resultado.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Resultado: </span></p></body></html>"))
        self.btn_Predecir.setText(_translate("MainWindow", "Predecir"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

